### ISSUE TITLE
Failed to load the jquery-snippets package

### ISSUE THREAD

**Issue by snipe** [james2doyle/atom-jquery-snippets#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets) package, v0.4.0

### Stack Trace

Failed to load the jquery-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:1:1)
  at /Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:5:3
  at Object.<anonymous> (/Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:52:5)
  at Object.<anonymous> (/Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets.coffee:1:22)
  at Object.<anonymous> (/Users/agianotto/.atom/packages/jquery-snippets/lib/jquery-snippets.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:433:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:316:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
 19x -9:22.1.0 core:backspace (atom-text-editor.editor.mini)
     -4:46.4.0 core:confirm (atom-text-editor.editor.mini)
     -4:31.5.0 core:select-all (atom-text-editor.editor.mini)
     -4:29.1.0 core:backspace (atom-text-editor.editor.mini)
  2x -4:27.4.0 core:confirm (atom-text-editor.editor.mini)
     -0:34.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:31.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
jquery-snippets, v0.4.0
laravel, v0.7.0
linter, v0.12.1
linter-bootlint, v0.0.5
minimap, v4.8.0
project-palette-finder, v2.4.17
sass-autocompile, v0.6.2
sassbeautify, v0.2.0
save-session, v0.13.5
tabular, v0.1.0
travis-ci-status, v0.14.0

# Dev
No dev packages
```

**Comment by james2doyle** [comment]
Update the package and try again. There was some depreciation fixes just pulled in.

**Comment by snipe** [comment]
Thanks! ![high-five](https://cloud.githubusercontent.com/assets/197404/7459010/c0cb2c8a-f24d-11e4-8197-562892adb101.gif)
